# config.yaml: Master configuration for the grid search experiment

# --- Search Space Definition ---
# Defines the grid search range for alpha and beta.
search_space:
  alpha:
    min: 0.5
    max: 2.5
    step: 0.2  # Use a coarser step for initial tests, then refine.
  beta:
    min: 0.5
    max: 5.0
    step: 0.5

# --- Path Configuration ---
# All paths should be relative to main_experiment.py
paths:
  base_model_config: "models/yolo12.yaml"
  generated_configs_dir: "models/generated_configs"
  progress_file: "progress.json"
  dataset_config: "../ultralytics/cfg/datasets/VisDrone.yaml"
  log_dir: "logs"

# --- Training Parameters ---
# Fixed parameters for every training run.
train_params:
  project_name: "VisDrone_AB_Search" # Main folder for all runs
  run_name_prefix: "yolo12"         # Prefix for each run folder
  model_size: "n"
  epochs: 100
  imgsz: 640
  batch: 16
  seed: 0
  # Add any other fixed parameters you need, e.g., optimizer, lr0, etc.